# -*- coding: utf-8 -*-
"""DataLake e Data Warehouse - Aula 3 - exercícios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYwA3Htqka93b6jC-GNzLipiIh5vgkD9
"""

# Instalação do Java 8 (necessário para Spark)
!apt-get update > /dev/null
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

# Instalação do PySpark
!pip install pyspark --quiet

# Verificação da versão do Java
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
!java -version

from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

conf = SparkConf().set('spark.ui.port', '4050').setAppName("twitter").setMaster("local[*]")
sc = SparkContext.getOrCreate(conf=conf)

from google.colab import drive
drive.mount('/content/drive')

url = "/content/drive/My Drive/Colab Notebooks/tweets.csv"
df = spark.read.option("inferrSchema", True).option("header", True).csv(url)
df.printSchema()

df.write.saveAsTable("tweets")

spark.sql("SELECT Sentiment, COUNT(*) FROM tweets GROUP BY Sentiment").show()

from pyspark.sql import HiveContext
HiveContext = HiveContext(sc)
hiveQuery = "select SentimentText from tweets where Sentiment = 'pos';"
dfPos = df = HiveContext.sql(hiveQuery)
rddPos = dfPos.rdd

stopWords = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you','your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her',
             'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those',
             'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do','does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if',
             'or', 'because', 'as','until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above',
             'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once','here', 'there', 'when', 'where', 'why', 'how',
             'all', 'any', 'both', 'each', 'few','more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 'can', 'will',
             'just', 'don', 't', 's', 'should', 'now']

contadorPalavras = rddPos.map(lambda x:x.SentimentText.replace(',','').replace('.', ' ').replace('-','').lower()) \
 .flatMap(lambda x: x.split()) \
 .filter(lambda x: x not in stopWords) \
 .map(lambda x: (x,1)) \
 .reduceByKey(lambda x,y:x+y) \
 .map(lambda x:(x[1],x[0])) \
 .sortByKey(False)

contadorPalavras.take(10)

