# -*- coding: utf-8 -*-
"""POO_Aula3a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/dipucriodigital/engenharia-de-software/blob/main/programacao-orientada-a-objetos/POO_Aula3a.ipynb

# Programação Orientada a Objetos - Prof. Tatiana Escovedo

---

## Aula 03: Boas práticas de OO e de codificação em Python
### Prática 5: SOLID e Guia de Estilos

## SOLID

### Princípio da Responsabilidade Única
"""

class Animal:

    def __init__(self, nome):
        self.__nome = nome

    def get_nome(self):
        return self.__nome

    def salvar(self):
        # Salva o animal no banco de dados
        pass

class Animal:

    def __init__(self, nome):
        self.__nome = nome

    def get_nome(self):
        return self.__nome


class AnimalDAO:

    def salvar(self, animal: Animal):
        # Salva o animal no banco de dados
        pass

"""### Princípio Aberto/Fechado"""

class Animal:

    def __init__(self, nome):
        self.__nome = nome

    def get_nome(self):
        return self.__nome

    def faz_som(self):
        if self.__nome == "Cachorro":
            print("Au Au")
        if self.__nome == "Gato":
            print("Miau")

class Animal:

    def __init__(self, nome):
        self.__nome = nome

    def get_nome(self):
        return self.__nome

    def faz_som(self):
        pass


class Cachorro(Animal):

    def faz_som(self):
        print("Au Au")


class Gato(Animal):
    def faz_som(self):
        print("Miau")

"""### Princípio da Substituição de Liskov"""

class Animal:
    pass


class Cachorro(Animal):

    def latir(self):
        print("Au Au")


class Gato(Animal):

    def miar(self):
        print("Miau")


class Dono:

    def passear(self, cachorro: Cachorro):
        cachorro.latir()

class Animal:

    def faz_som(self):
        pass


class Cachorro(Animal):

    def faz_som(self):
        self.__latir()

    def __latir(self):
        print("Au Au")


class Gato(Animal):

    def faz_som(self):
        self.__miar()

    def __miar(self):
        print("Miau")


class Dono:

    def passear(self, animal: Animal):
        animal.faz_som()

"""### Princípio da Segregação de Interfaces"""

class ImpressoraFazTudo:

    def imprime(self):
        pass

    def digitaliza(self):
        pass

    def envia_fax(self):
        pass

class ImpressoraMultifuncional(ImpressoraFazTudo):

    def imprime(self):
        pass

    def escaneia(self):
        pass

    def envia_fax(self):
        pass

class Impressora:

    def imprime(self):
        pass


class Digitalizadora:

    def digitaliza(self):
        pass

class Fax:

    def envia_fax(self):
        pass

class ImpressoraMultifuncional(Impressora, Digitalizadora, Fax):

    def imprime(self):
        pass

    def escaneia(self):
        pass

    def envia_fax(self):
        pass


# A classe ImpressoraPadrao pode utilizar somente o método que precisa:
class ImpressoraPadrao(Impressora):

    def imprime(self):
        pass

"""### Princípio da Inversão de Dependências"""

class Animal:

    def faz_som(self):
        pass


class Cachorro(Animal):

    def faz_som(self):
        self.latir()

    def latir(self):
        print("Au Au")


class Gato(Animal):

    def faz_som(self):
        self.miar()

    def miar(self):
        print("Miau")

class Dono:

    def passear(self, cachorro: Cachorro):
        cachorro.latir()

class Dono:

  def passear(self, animal: Animal):
        animal.faz_som()

"""## Guia de Estilos"""

import this