# -*- coding: utf-8 -*-
"""POO_Aula2b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/dipucriodigital/engenharia-de-software/blob/main/programacao-orientada-a-objetos/POO_Aula2b.ipynb

# Programação Orientada a Objetos - Prof. Tatiana Escovedo

---

## Aula 02: Os 4 pilares da Orientação a Objetos
### Prática 4: Orientação a Objetos

## Introdução à Orientação a Objetos
"""

class Pessoa:

    def __init__(self, nome):
        self.nome = nome

    def __str__(self):
        return self.nome

pessoa_1 = Pessoa("João")
print(pessoa_1)

pessoa_2 = Pessoa("Maria")
print(pessoa_2)

class ListaDeNumeros:

    def __init__(self, numeros):
        self.numeros = numeros

    def __str__(self):
        return ", ".join([str(n) for n in self.numeros])

    def soma(self):
        return sum(self.numeros)

    def media(self):
        return self.soma()/len(self.numeros)

minha_lista = ListaDeNumeros([1,3,5,7,9])

print(f"A soma de {minha_lista} é {minha_lista.soma()}")
print(f"A média de {minha_lista} é {minha_lista.media()}")

class Pessoa:

    num_pessoas = 0

    def __init__(self, nome):
        self.nome = nome
        Pessoa.num_pessoas +=1

nomes = ['João', 'Paulo', 'George', 'Ringo']
pessoas = [Pessoa(nome) for nome in nomes]

Pessoa.num_pessoas

pessoas[0].nome

class Calculadora:

    def soma(self, a, b):
        res = a + b
        return res

calculadora = Calculadora()
calculadora.soma(2,3)

"""## Encapsulamento"""

class Conta:

    def __init__(self, numero, saldo):
        self.numero = numero
        self.__saldo = saldo

conta1234 = Conta(1234, 750.84)
conta1234.numero

conta1234.__saldo

conta1234._Conta__saldo

dir(conta1234)

conta1234.__saldo = 1000

conta1234._Conta__saldo

dir(conta1234)

class Conta:

    def __init__(self, numero, saldo):
        self.__numero = numero
        self.__saldo = saldo

    def consulta_saldo(self):
        return self.__saldo

conta1234 = Conta(1234, 750.84)
conta1234.consulta_saldo()

"""## Herança"""

# Classe Pessoa
class Pessoa:

    def __init__(self, nome, login, senha):
        self.__nome = nome
        self.__login = login
        self.__senha = senha

    def consulta_nome(self):
        return self.__nome

# Classe Aluno
class Aluno(Pessoa):

    def __init__(self, nome, login, senha, curso):
        Pessoa.__init__(self, nome, login, senha)
        self.__curso = curso

    def consulta_curso(self):
        return self.__curso

# Classe Professor
class Professor(Pessoa):

    def __init__(self, nome, login, senha, titulacao):
        Pessoa.__init__(self, nome, login, senha)
        self.__titulacao = titulacao

    def consulta_titulacao(self):
        return self.__titulacao

pessoa1 = Pessoa('Maria', 'mary', 'm123')
print(pessoa1.consulta_nome())

aluna1 = Aluno('Viviane', 'vivi', 'v123', 'Informática')
print(aluna1.consulta_nome())
print(aluna1.consulta_curso())

prof1 = Professor('Tatiana', 'tati', 't123', 'Doutorado')
print(prof1.consulta_nome())
print(prof1.consulta_titulacao())

"""## Polimorfismo"""

class EntradaUniversidade:

    def __init__(self):
        pass

    def permite_entrada(self, pessoa):
        print("Pode entrar, " + pessoa.consulta_nome())

entrada = EntradaUniversidade()
entrada.permite_entrada(prof1)

# Classe Coordenador
class Coordenador(Pessoa):
    def __init__(self, nome, login, senha):
        Pessoa.__init__(self, nome, login, senha)

coord1 = Coordenador('Marcos', 'mk', 'm123')
entrada.permite_entrada(coord1)

"""## Abstração"""

import abc

class Pessoa(abc.ABC):

    def __init__(self, nome, login, senha):
        self.nome = nome
        self.login = login
        self.senha = senha

    @abc.abstractmethod
    def consulta_nome(self):
        raise NotImplementedError()

pessoa1 = Pessoa()

"""## Associação, Agregação e Composição"""

class Aluno(Pessoa):

    def __init__(self, nome, login, senha, curso, orientador):
        Pessoa.__init__(self, nome, login, senha)
        self.__curso = curso
        self.__orientador = orientador

    def consulta_curso(self):
        return self.__curso

    def consulta_orientador(self):
        return self.__orientador

    def consulta_nome(self):
        return self.nome

professorMarcos = Professor('Marcos', 'mk', 'm123', 'Doutor')

novoAluno = Aluno('Isabela', 'isa', 'i123', 'Engenharia', professorMarcos)

import datetime

class Historico():

    def __init__(self):
        self.__data_matricula = datetime.datetime.today()
        self.__ocorrencias = []

    def imprime(self):
        print("Matriculado em {}".format(self.__data_matricula))
        print("Ocorrências:")
        for o in self.__ocorrencias:
            print("- ", o)

    def add_ocorrencia(self, ocorrencia):
        self.__ocorrencias.append(ocorrencia)

class Aluno(Pessoa):

    def __init__(self, nome, login, senha, curso, orientador):
        Pessoa.__init__(self, nome, login, senha)
        self.__curso = curso
        self.__orientador = orientador
        self.__historico = Historico()

    def consulta_curso(self):
        return self.__curso

    def consulta_orientador(self):
        return self.__orientador

    def consulta_nome(self):
        return self.__nome

    def gera_ocorrencia(self, ocorrencia):
        self.__historico.add_ocorrencia(ocorrencia)

    def consulta_historico(self):
        self.__historico.imprime()

novoAluno = Aluno('Isabela', 'isa', 'i123', 'Engenharia', professorMarcos)
novoAluno.gera_ocorrencia("Matriculou-se em Calculo 1")
novoAluno.gera_ocorrencia("Nota final de Calculo 1: 9,7")
novoAluno.consulta_historico()