# -*- coding: utf-8 -*-
"""POO_Aula1b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/dipucriodigital/engenharia-de-software/blob/main/programacao-orientada-a-objetos/POO_Aula1b.ipynb

# Programação Orientada a Objetos - Prof. Tatiana Escovedo

---

## Aula 01: Introdução a Python e Orientação a Objetos

### Prática 2: Criando os primeiros programas em Python

### Programa 1: Quem é você?
"""

nome = input("Como posso te chamar?") # mensagem a ser exibida na tela
print("Olá,", nome) # imprime "Olá" concatenado com o nome inserido pelo usuário

"""### Programa 2: Aluno aprovado?"""

print("**************************************")
print("O aluno foi aprovado?")
print("**************************************")

nota_1 = float(input("Nota 1: "))
nota_2 = float(input("Nota 2: "))
nota_3 = float(input("Nota 3: "))

media = (nota_1 + nota_2 + nota_3)/3 # calcula a média

if media >= 7:
    print("O aluno foi APROVADO! Sua média foi %.2f" % media)
elif media < 3:
    print("O aluno foi REPROVADO! Sua média foi %.2f" % media)
else:
    print("O aluno ficou em PROVA FINAL! Sua média foi %.2f" % media)

"""### Programa 3: Calculadora simples em Python"""



def bem_vindo():
    print("**************************************")
    print("Calculadora simples em Python")
    print("**************************************")
    calcular()

def calcular():

    print("\nQual operação deseja executar? (1) Soma (2) Subtração (3) Multiplicação (4) Divisão (5) Outra")
    operacao = int(input("Digite a operação a ser realizada: "))

    if(operacao != 1 and operacao != 2 and operacao != 3 and operacao != 4 ):
        print("Desculpe, esta calculadora ainda não suporta outras operações. Por favor, execute o programa novamente.")
        return

    primeiro_numero = int(input("Digite o primeiro número: "))
    segundo_numero = int(input("Digite o segundo número: "))

    if(operacao == 1):
        print("O resultado é", primeiro_numero + segundo_numero)
    elif(operacao == 2):
        print("O resultado é", primeiro_numero - segundo_numero)
    elif(operacao == 3):
        print("O resultado é", primeiro_numero * segundo_numero)
    else:
        print("O resultado é", primeiro_numero / segundo_numero)

    calcular_outra_vez()


def calcular_outra_vez():
    outra_vez = input("Deseja realizar outra operação? Por favor, digite S para SIM ou N para NÃO: ")

    if outra_vez.upper() == 'S':
        calcular()
    elif outra_vez.upper() == 'N':
        print('Até a próxima!')
    else:
        print("Opção inválida.")
        calcular_outra_vez()

bem_vindo()