# -*- coding: utf-8 -*-
"""POO_Aula3b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/dipucriodigital/engenharia-de-software/blob/main/programacao-orientada-a-objetos/POO_Aula3b.ipynb

# Programação Orientada a Objetos - Prof. Tatiana Escovedo

---

## Aula 03: Boas práticas de OO e de codificação em Python
### Prática 6: Boas práticas

## Código inicial
"""

class atendimentoalunos:
    codigo=0
    fila=[]
    alunosatendidos=[]
    senhaatual=""

    def gerasenhaatual(self):
        self.senhaatual=f"A{self.codigo}"
    def atualizafila(self):
        self.codigo+=1
        self.gerasenhaatual()
        self.fila.append(self.senhaatual)
    def atendealuno(self, guiche):
        alunoatual=self.fila.pop(0)
        self.alunosatendidos.append(alunoatual)
        return f"{alunoatual} - Guichê {guiche}"

# Código de teste

secretaria = atendimentoalunos()
secretaria.atualizafila()
secretaria.atualizafila()
secretaria.atualizafila()
secretaria.atualizafila()

print("\t=== Pessoas atualmente na fila:", secretaria.fila)

print(secretaria.atendealuno("3"))
print(secretaria.atendealuno("1"))

print("\t=== Pessoas atendidas:", secretaria.alunosatendidos)

print("\t=== Pessoas atualmente na fila:", secretaria.fila)

"""## Melhoria"""

# Melhorando o código segundo a PEP8:
# - Typehints nas variáveis e retornos de métodos
# - Nomenclatura da classe, métodos e atributos
# - Linha em branco entre métodos
# - Espaços entre operadores

class AtendimentoAlunos:
    codigo: int = 0
    fila = []
    alunos_atendidos = []
    senha_atual: str = ""

    def gera_senha_atual(self) -> None:
        self.senha_atual = f"A{self.codigo}"

    def atualiza_fila(self) -> None:
        self.codigo += 1
        self.gera_senha_atual()
        self.fila.append(self.senha_atual)

    def atende_aluno(self, guiche: str) -> str:
        aluno_atual = self.fila.pop(0)
        self.alunos_atendidos.append(aluno_atual)
        return f"{aluno_atual} - Guichê {guiche}"

# Novo código de teste

secretaria = AtendimentoAlunos()
secretaria.atualiza_fila()
secretaria.atualiza_fila()
secretaria.atualiza_fila()
secretaria.atualiza_fila()

print("\t=== Pessoas atualmente na fila:", secretaria.fila)

print(secretaria.atende_aluno("3"))
print(secretaria.atende_aluno("1"))

print("\t=== Pessoas atendidas:", secretaria.alunos_atendidos)

print("\t=== Pessoas atualmente na fila:", secretaria.fila)

"""## Modificações solicitadas pelo cliente"""

class AtendimentoProfessores:
    codigo: int = 0
    fila = []
    professores_atendidos = []
    senha_atual: str = ""

    def gera_senha_atual(self) -> None:
        self.senha_atual = f"P{self.codigo}" # senha com prefixo P em vez de A

    def atualiza_fila(self) -> None:
        self.codigo += 1
        self.gera_senha_atual()
        self.fila.append(self.senha_atual)

    def atende_professor(self, guiche: str) -> str:
        professor_atual = self.fila.pop(0)
        self.professores_atendidos.append(professor_atual)
        return f"Senhor(a) {professor_atual}, dirija-se ao guichê {guiche}" # tratamento

# Novo código de teste

secretaria = AtendimentoProfessores()
secretaria.atualiza_fila()
secretaria.atualiza_fila()
secretaria.atualiza_fila()
secretaria.atualiza_fila()

print("\t=== Pessoas atualmente na fila:", secretaria.fila)

print(secretaria.atende_professor("3"))
print(secretaria.atende_professor("1"))

print("\t=== Pessoas atendidas:", secretaria.professores_atendidos)

print("\t=== Pessoas atualmente na fila:", secretaria.fila)

"""## Melhoria"""

# Classe AtendimentoPessoas

import abc

class AtendimentoPessoas:
    codigo: int = 0
    fila = []
    pessoas_atendidas = []
    senha_atual: str = ""

    @abc.abstractmethod
    def gera_senha_atual(self):
        ...

    @abc.abstractmethod
    def atende_pessoa(self, guiche: int):
        ...

    def atualiza_fila(self) -> None:
        AtendimentoPessoas.codigo += 1 # codigo agora é estática
        self.gera_senha_atual()
        AtendimentoPessoas.fila.append(self.senha_atual) # fila agora é estática


# Classe AtendimentoAlunos

class AtendimentoAlunos(AtendimentoPessoas):

    def gera_senha_atual(self) -> None:
        self.senha_atual = f"A{self.codigo}"

    def atende_pessoa(self, guiche: int) -> str:
        aluno_atual = self.fila.pop(0)
        AtendimentoPessoas.pessoas_atendidas.append(aluno_atual)
        return f"{aluno_atual} - Guichê {guiche}"


# Classe AtendimentoProfessores

class AtendimentoProfessores(AtendimentoPessoas):

    def gera_senha_atual(self) -> None:
        self.senha_atual = f"P{self.codigo}"

    def atende_pessoa(self, guiche: int) -> str:
        professor_atual = self.fila.pop(0)
        AtendimentoPessoas.pessoas_atendidas.append(professor_atual)
        return f"Senhor(a) {professor_atual}, dirija-se ao guichê {guiche}" # tratamento

# Novo código de teste

secretaria_alunos = AtendimentoAlunos()
secretaria_professores = AtendimentoProfessores()

secretaria_alunos.atualiza_fila()
secretaria_alunos.atualiza_fila()
secretaria_professores.atualiza_fila()
secretaria_professores.atualiza_fila()
secretaria_alunos.atualiza_fila()
secretaria_alunos.atualiza_fila()
secretaria_professores.atualiza_fila()
secretaria_professores.atualiza_fila()

print("\t=== Pessoas atualmente na fila:", AtendimentoPessoas.fila)

print(secretaria_alunos.atende_pessoa("3"))
print(secretaria_alunos.atende_pessoa("1"))
print(secretaria_professores.atende_pessoa("2"))
print(secretaria_professores.atende_pessoa("1"))

print("\t=== Pessoas atendidas:", AtendimentoPessoas.pessoas_atendidas)

print("\t=== Pessoas atualmente na fila:", AtendimentoPessoas.fila)