# -*- coding: utf-8 -*-
"""POO_Aula2a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/dipucriodigital/engenharia-de-software/blob/main/programacao-orientada-a-objetos/POO_Aula2a.ipynb

# Programação Orientada a Objetos - Prof. Tatiana Escovedo

---

## Aula 02: Os 4 pilares da Orientação a Objetos

### Prática 3: Introdução à Orientação a Objetos

### Exemplo de código 1: Definição de Classe e instanciação dos objetos
"""

# Definição da classe
class Aluno:

    def __init__(self):
        self.nome = "Zé"
        self.idade = 18

    def dobra_idade(self):
        return self.idade * 2


# Instanciação dos objetos

aluno_1 = Aluno()
aluno_1.nome = "Maria" # definindo que o nome do aluno_1 é "Maria"


aluno_2 = Aluno()
aluno_2.idade = 21 # definindo que a idade do aluno_2 é 21

print(aluno_1.nome) # imprime Maria (valor que definimos)
print(aluno_2.nome) # imprime Zé (valor default)

print(aluno_1.dobra_idade()) # dobra a idade 18 (valor default)
print(aluno_2.dobra_idade()) # dobra a idade 21 (valor que definimos)

# ao mudar o valor de nome em aluno_1, o aluno_2 continua inalterado
aluno_1.nome = "Ana"
print("Nome do aluno_1:", aluno_1.nome)
print("Nome do aluno_2:", aluno_2.nome)

"""### Exemplo de código 2: Parâmetro self"""

class Calculadora:

    def __init__(self):
        self.valor_interno = 5

    def adiciona(self, numero):
        # não podemos chamar a variável "valor_interno" sem "self" porque "valor" é um atributo de Calculadora
        return self.valor_interno + numero;

total = Calculadora()
print("resultado = %d" % total.adiciona(3)) # self pegará o valor 5 de valor_interno e o valor 3 irá para numero

"""### Exemplo de código 3: Método \_\_init__"""

class Carro:

    def __init__(self):
        self.cor = "preto"

# um novo carro é criado com cor = "preto"
carro_1 = Carro()
print(carro_1.cor)

# alterando o valor da color de carro_1 para "branco"
carro_1.cor = "branco"
print(carro_1.cor)

class Carro2:

    def __init__(self, cor):
        self.cor = cor

# um novo carro é criado com cor = "azul"
carro_2 = Carro2("azul")
print(carro_2.cor)

# alterando o valor da color de carro_2 para "branco"
carro_2.cor = "branco"
print(carro_2.cor)