# -*- coding: utf-8 -*-
"""POO_Aula1a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/dipucriodigital/engenharia-de-software/blob/main/programacao-orientada-a-objetos/POO_Aula1a.ipynb

# Programação Orientada a Objetos - Prof. Tatiana Escovedo

---

## Aula 01: Introdução a Python e Orientação a Objetos

### Prática 1: Introdução à Linguagem Python

## Básico de Python

## Primeiro Programa
"""

# Isto é um comentário de apenas uma linha
print("Hello, World!")

"""### Zen do Python"""

import this

"""## Variáveis"""

# Variáveis: Definição e tipos

# Declarando 4 variáveis e atribuindo valores a elas
uma_string = "Aluno"
um_inteiro = 7
um_float = 7.584
um_booleano = True

# Imprimindo o valor e o tipo de uma das variáveis
print(um_float)
print(type(um_float))

# Casting: Convertendo a variável do tipo float para int e para string
print(int(um_float))
print(str(um_float))

# Operações Aritméticas

# Soma, Subtração, Multiplicação e Divisão
resultado_1 = 7 + 5
resultado_2 = um_inteiro - resultado_1
resultado_3 = resultado_2 * 3
resultado_4 = resultado_3 / 4

# Imprimindo os resultados concatenando uma string com o resultado numérico
print("Resultado da soma = " + str(resultado_1))
print("Resultado da subtração = " + str(resultado_2))
print("Resultado da multiplicação = " + str(resultado_3))
print("Resultado da divisão = " + str(resultado_4))

# Potenciação e Resto da Divisão
resultado_5 = 2 ** 4
resultado_6 = 13 % 4

# Imprimindo os resultados concatenando uma string com o resultado numérico
print("Resultado da potenciação = " + str(resultado_5))
print("Resultado do resto da divisão = " + str(resultado_6))

# Incremento e Decremento

# Decrementando 3 unidades
um_inteiro -= 3
print("Resultado: " + str(um_inteiro)) # 7 - 3 = 4 --> agora um_inteiro é 4

# Incrementando 5 unidades
um_inteiro += 5
print("Resultado: " + str(um_inteiro)) # 4 + 5 = 9 --> agora um_inteiro é 9

# Operadores de Igualdade

variavel_um = 1
variavel_dois = 2
variavel_tres = 3

print(1 == variavel_um)
print(2 == variavel_um)

equal = (variavel_um == variavel_dois) # os () são opcionais neste caso, mas ajudam a legibilidade
not_equal = (variavel_um != variavel_dois)

print("Um é igual a dois? " + str(equal))
print("Um é diferente de dois? " + str(not_equal))

# Operadores de Comparação

print("Um é maior do que dois? " + str(variavel_um > variavel_dois))
print("Um é menor do que dois? " + str(variavel_um < variavel_dois))

# Operadores Lógicos and (e) e or (ou)

print((2 > 1) and (3 < 5)) # V V
print((2 > 1) and (1 > 3)) # V F

print((3 < 5) or (2 > 1)) # V V
print((0 > 1) or (0 == -1)) # F F
print((0 < 1) or (0 == -1)) # V F

"""## Strings"""

# Concatenação

programacao = "Programação" # pode ser tanto delimitada por aspas duplas...
oo = 'OO' #... quanto por aspas simples, mas sempre combinando
programacao_oo = programacao + " " + oo
print(programacao_oo)

# Tamanho

print(len(programacao_oo))

# Indexação e Substrings

frase = "Python é muito divertido!"

# A indexação começa com 0
print(frase[3])

# use -1 para pegar a última letra
print(frase[-1])

# -2 pega a penúltima letra
print(frase[-2])

# string[start:end] - end não é incluso
print(frase[:4])
print(frase[10:])
print(frase[5:10])
print(frase[:])

# Multiplicação de uma string por um número

ola = "olá"
sete_olas = ola * 7
print(sete_olas)

# Operador in

programacao_python = "Programação em Python"

# checa se a string contém "Python"
print("Python" in programacao_python)

# checa se a string contém "python"
print("python" in programacao_python)

# checa se a string contém "abacate"
print("abacate" in programacao_python)

# Escaping

print("Estou estudando\n" + programacao_python) # \n = nova linha

# Maiúsculas e Minúsculas

print(programacao_python.lower()) # todas minúsculas
print(programacao_python.upper()) # todas maiúsculas

tudo_minuscula = "aula de python"
print(tudo_minuscula.capitalize()) # primeira letra maiúscula

# Formatação

nome = "Belinha"
numero_inteiro = 7
numero_decimal = 7.584

print("Olá, meu nome é %s! Tenho %d anos e %d reais" % (nome, numero_inteiro, numero_decimal)) # float impresso como int
print("Olá, meu nome é %s! Tenho %d anos e %f reais" % (nome, numero_inteiro, numero_decimal)) # float impresso como float
print("Olá, meu nome é %s! Tenho %d anos e %.2f reais" % (nome, numero_inteiro, numero_decimal)) # float impresso como float com 2 casas decimais

"""## Coleções"""

# Listas

numeros = [1, 10, 100, 1000]
print(numeros)

# imprimir o elemento de índice 2 - inicia no 0
print(numeros[2])

# Operações de Listas

# incluir 2 itens na lista usando +=
numeros += [10000, 100000]
print(numeros)

# incluir 1 item na lista usando append
numeros.append(1000000)
print(numeros)

# substituir os itens nas posições 1 e 2 por 7
# [índice_incluído:índice_excluído]
numeros[1:3] = [7]
print(numeros)

# remover os itens nas posições 1 e 2 da lista
numeros[1:3] = []
print(numeros)

# tamanho da lista
print(len(numeros))

# Tuplas

naipes = ('copas', 'ouros', 'espadas', 'paus')
print(naipes)

# Dicionários

# criar e imprimir um dicionário
notas = {"Ana": 8, "Maria": 5, "Thais": 10}
print(notas)

# acessar o valor correspondente à chave "Thais"
print(notas["Thais"])

# incluir novo item
notas["Zaira"] = 9
print(notas)

# remover item
del notas["Thais"]
print(notas)

# checar se notas contém o item "Maria"
print("Maria" in notas)

"""## Condições"""

nome = "Ana"
idade = 25

# Comando if (condição se)

if nome == "Ana": # V
    print("Passou!")

if nome == "Ana" or idade == 17:   # V ou V = V
    print("Passou de novo!")
    print("%s tem %d anos" %(nome, idade))

# Comandos if, elif e else

dias = ["sábado", "domingo"]
if len(dias) == 0:
    print("Lista vazia")
elif len(dias) == 1:
    print("Só um dia")
else:
    print("Tamanho %d" % len(dias))

"""## Loops"""

# Loop for
for i in range(6):
    print(i)

# OBS: A função range() pode ser representada de três formas diferentes:
# range(stop_value) : Considera o ponto inicial como zero.
# range(start_value, stop_value) : Gera a sequência com base no valor inicial e final.
# range(start_value, stop_value, step_size): Gera a sequência incrementando o valor inicial usando o tamanho do passo até atingir o valor final.

# Loop for - outro exemplo
pares = [2, 4, 6, 8]
for i in range(len(pares)):
    print("Índice %d - Valor %d " % (i, pares[i]))

# Loop for usando string

hello_world = "Hello, World!"

# imprimir cada caracter
for ch in hello_world:
    print(ch)

# contar a quantidade de caracteres usando loop
length = 0
for ch in hello_world:
    length += 1
print("Número de caracteres: %d " % length)

# Loop While
numero = 1

# imprimir de 1 a 7
while numero <= 7:
    print(numero)
    numero += 1

# imprimir os quadrados menores que 25
numero = 1
quadrado = 1

while quadrado <= 24:
    quadrado = numero ** 2
    print("Número %d - Quadrado %d" % (numero, quadrado))
    numero += 1

print("Ao sair do while, numero tem o valor %d" % numero)

# Break

count = 0

# loop infinito - nunca é False
while True:
    print(count)
    count += 1
    if count >= 5:
      break # sai do loop

naipes = ['copas', 'ouros', 'espadas', 'paus']

# loop infinito - nunca é False
while True:
    # pop(): retira e retorna o último item da lista
    elemento = naipes.pop()
    print(elemento)
    if elemento == "espadas":
        break

# Continue

for i in range(5):
    if i == 3:
       continue # pula o resto do código e move para a próxima iteração do loop
    print(i)

# imprimir somente os ímpares
for x in range(10):
    if (x % 2) == 0: # é par
        # pula print(x) para este loop
        continue
    print("Número %d" % x)

"""## Funções"""

# Funções

# definir uma função chamada hello_world
def hello_world():
    print("Hello, World!")
    print("Oi, Mundo!")
    print("Salut, Monde!")
    print("Hola, Mundo!")

# chamar a função 3 vezes
for i in range(3):
    hello_world()

# Funções com parâmetros

# x é um parâmetro
def uma_funcao(x):
    print("x = %d" % x)

# passar 5 para a função. Aqui, 5 é um argumento passado para a função
uma_funcao(5)

# Funções com retorno

# função que retorna a soma de dois números
def soma(a, b):
    return a + b

c = soma(7, 5)
print("c = %d" % c)

# Função com parâmetros default (padrão)

def multiplica(a, b=2):
    return a * b

print(multiplica(5, 84))

# como b tem um valor padrão, podemos passar apenas um argumento
print(multiplica(7))